---
title: "RWorksheet_Francisco#2"
author: "Enrique E. Francisco"
date: "2024-09-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1.)A. 
A <- -5:5
A
#Output: [1] -5 -4 -3 -2 -1  0  1  2  3  4  5, the output ranges from -5 to 5

#1).B
#The value of x will from 1 to 7
x <- 1:7
x
```

```{r}
#2.
B <- seq(1, 3, by=0.2)
B
#Output:[1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0
#The output start from 1 and adds 0.2 until 3.
```

```{r}
#3.
age <- list(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,18)
#3.)A:22
age[3]
#3.B: 28,36
age[c(2,4)]
#3.C: The output prints all the age vector without the 4th and 12th element
age[-c(4,12)]
```


```{r}
#4.
names <- c("first"=3, "second"=0, "third"=9)
names
#4.A: the outputs prints "first" and "third" as columns and then their assigned values.
names[c("first", "third")]
#4.B: first second  third 
#     3      0      9 

```

```{r}
#5.
x <- -3:2
#5.A: The output will print 0 for the 2nd element on the vector instead of -2
x[2] <- 0
x
#5.B 
#Output:[1] -3  0 -1  0  1  2
```

```{r}
#6.A
diesel_fuel <- data.frame(Month = c("Jan", "Feb", "March", "Apr", "May", "June"),
Price_per_Liter = c("52.50", "57.25", "60.00", "65.00", "74.25", "54.00"),
Purchase_Quantity = c("25", "30", "40", "50", "10", "45"))
diesel_fuel

#6.B: The average fuel expenditure of Mr.Crus is 59.2625
diesel_fuel$Price_per_Liter <- as.numeric(diesel_fuel$Price_per_Liter)
diesel_fuel$Purchase_Quantity <- as.numeric(diesel_fuel$Purchase_Quantity)
avg_fuel_exp <- weighted.mean(diesel_fuel$Price_per_Liter, diesel_fuel$Purchase_Quantity)
avg_fuel_exp
```

```{r}
#7.A
NA_rivers <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
sd(rivers), min(rivers), max(rivers))
NA_rivers
#7.B
NA_rivers
#[1]    141.0000  83357.0000    591.1844    425.0000
#[5] 243908.4086    493.8708    135.0000   3710.0000

```

```{r}
#8.A
power_ranking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
celeb <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Sprinsteen", "Donal Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K. Rowling", "Brad Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Leno", "Celine Dion", "Kobe Bryant")
pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 60, 40, 47, 75, 25, 39, 45, 32, 40, 31)
power_ranking
celeb
pay
#8.B
Change <- which(celeb == "J.K. Rowling")
power_ranking[Change] <- 15
pay[Change] <- 90
#8.C
Forbes_ranks <- read.csv("/cloud/project/Worksheet2/PowerRanking.csv")
#8.D
Ranks <- Forbes_ranks[10:20,]
Ranks
save(Ranks, file = "/cloud/project/Worksheet2/Ranks.RData")
#8.E: the output prints the rows from 10 to 20.

```

```{r}
#9.A
library("openxlsx")
library("readxl")
hotelsvienna <- read_xlsx("/cloud/project/Worksheet2/hotels-vienna.xlsx")
#9.)B: It has 428 row dimensions and 24 column dimensions
dim(hotelsvienna)
#9.C 
column <- hotelsvienna[, c("country", "neighbourhood", "price","stars", "accommodation_type", "rating")]
#9.D
save(column, file ="/cloud/project/Worksheet2/new.RData")
#9.E
load("/cloud/project/Worksheet2/new.RData")
head(column, 6)
tail(column, 6)
```
   
     
```{r}
#10.A
vegetables <- list("Potato", "Carrot", "Onion", "Spinach", "Cabbage", "Eggplant", "Tomato", "Lettuce", "Radish", "Garlic")
vegetables
#10.B
vegetables <- append(vegetables, list("Cucumber", "Squash"))
vegetables
#10.C: 16 data points
vegetables <- append(vegetables, list("Cauliflower", "Asparagus", "Green Beans", "Beet Root"))
vegetables
length(vegetables)
#10.D: 13 vegetables were left
vegetables <- vegetables[-c(5, 10, 15)]
vegetables
```
     
     